06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/Condominio.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    [Table("TblCondominio")]
    public class Condominio
    {
        [HiddenInput]
        public int CondominioId { get; set; }
        [Required, MaxLength(40)]
        public string Nome { get; set; }
        public int Blocos { get; set; }
        public bool Ativo { get; set; }
        public Tipo Tipo { get; set; }

        public Sindico Sindico { get; set; }
        public int SindicoId { get; set; }

        public IList<Imovel> Imovel { get; set; }
        public int ImovelId { get; set; }

        public IList<CondominioContrutora> CondominioContrutoras { get; set; }

    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/CondominioContrutora.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class CondominioContrutora
    {

        public Condominio Condominio { get; set; }

        public int CondominioId { get; set; }

        public Construtora Construtora { get; set; }

        public int ConstrutoraId { get; set; }
    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/Construtora.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class Construtora
    {
        public int ConstrutoraId { get; set; }

        public string Nome { get; set; }

        public string Cnpj { get; set; }

        public IList<CondominioContrutora> CondominioContrutoras { get; set; }

    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _06_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/Imovel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class Imovel
    {

        public int imovelId { get; set; }

        public int Numero { get; set; }

        public float AreaUtil { get; set; }

        public Condominio Condominio { get; set; }

        public int CondominioId { get; set; }


    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/Sindico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public class Sindico
    {
        public int SindicoId { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }

    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Models/Tipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    public enum Tipo
    {
        Casa, Apartamento
    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Controllers/CondominioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _06_Fiap.Web.AspNet.Models;
using _06_Fiap.Web.AspNet.Persitences;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class CondominioController : Controller
    {
        private BancoContext _context;

        public CondominioController(BancoContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Pesquisar(string termoPesquisa)
        {
            var lista = _context.Condominios.Where(
                c => c.Nome.Contains(termoPesquisa)).Include(c => c.Sindico).ToList();
            return View("Listar", lista);
        }

        [HttpPost]
        public IActionResult Excluir(int id)
        {
            var cond = _context.Condominios.Find(id);
            _context.Condominios.Remove(cond);
            _context.SaveChanges();
            TempData["mensagem"] = "Excluido";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var cond = _context.Condominios.Include(c => c.Sindico)
                .Where(c => c.CondominioId == id).FirstOrDefault();
            return View(cond);
        }

        [HttpPost]
        public IActionResult Editar(Condominio condominio)
        {
            _context.Condominios.Update(condominio);
            _context.SaveChanges();
            TempData["mensagem"] = "Editado com sucesso!";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Listar()
        {
            return View(_context.Condominios.Include(c => c.Sindico).ToList());
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Condominio condominio)
        {
            _context.Condominios.Add(condominio);
            _context.SaveChanges();
            TempData["mensagem"] = "Cadastrado!";
            return RedirectToAction("Cadastrar");
        }
    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _06_Fiap.Web.AspNet.Models;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Controllers/ImovelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _06_Fiap.Web.AspNet.Models;
using _06_Fiap.Web.AspNet.Persitences;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class ImovelController : Controller
    {
        private BancoContext _context;

        public ImovelController(BancoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Imovel imovel)
        {
            _context.Imoveis.Add(imovel);
            _context.SaveChanges();

            TempData["mensagem"] = "Cadastrado!";
            return RedirectToAction("Cadastrar");

        }

    }
}

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Views/Condominio/Cadastrar.cshtml
@model  Condominio

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar</h1>

<mensagem texto="@TempData["mensagem"]"></mensagem>

<form asp-action="cadastrar" asp-controller="condominio">
    <partial name="_formulario" />
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
</form>

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Views/Condominio/Editar.cshtml
@model  Condominio

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<form asp-action="Editar" asp-controller="Condominio">
    <input asp-for="CondominioId" />
    <partial name="_formulario"/>
    <input type="submit" value="Editar" class="btn btn-success" />
</form>

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Views/Condominio/Listar.cshtml
@model List<Condominio>

@{
    ViewData["Title"] = "Listar";
}

<h1>Listar</h1>

<mensagem texto="@TempData["mensagem"]"></mensagem>

<form asp-action="pesquisar" method="get" class="form-inline">
    <input placeholder="Digite o nome" type="text" name="termoPesquisa" class="form-control" />
    <input type="submit" value="Buscar" class="ml-2 btn btn-success" />
</form>
<br />
<table class="table">
    <tr>
        <th>Nome</th>
        <th>Blocos</th>
        <th>Ativo</th>
        <th>Tipo</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Blocos</td>
            <td>@(item.Ativo ? "Sim" : "Não")</td>
            <td>@item.Tipo</td>
            <td>
                <a class="btn btn-outline-dark btn-sm" asp-action="Editar" asp-route-id="@item.CondominioId">Editar</a>
                <!-- Button trigger modal -->
                <button onclick="codigo.value = @item.CondominioId" type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                    Excluir
                </button>
            </td>
        </tr>
    }
</table>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir?
            </div>
            <div class="modal-footer">
                <form asp-action="Excluir">
                    <input name="id" type="hidden" id="codigo"/> 
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Views/Condominio/_formulario.cshtml
@model  Condominio

<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Blocos"></label>
    <input asp-for="Blocos" class="form-control" />
</div>
<div class="form-group">
    <input asp-for="Ativo" />
    <label asp-for="Ativo"></label>
</div>
<div class="form-group">
    <label asp-for="Tipo"></label>
    <select asp-for="Tipo" class="form-control"
            asp-items="@Html.GetEnumSelectList<Tipo>()">
        <option>Selecione</option>
    </select>
</div>
<div class="form-group">
    <label asp-for="Sindico.Nome"></label>
    <input asp-for="Sindico.Nome" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Sindico.Email"></label>
    <input asp-for="Sindico.Email" class="form-control" />
</div>

06-Fiap.Web.AspNet/06-Fiap.Web.AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _06_Fiap.Web.AspNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_06_Fiap.Web.AspNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - _06_Fiap.Web.AspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>